### ISSUE TITLE
ビルド環境と実行環境違う

### ISSUE THREAD

**Issue by yhay81** [dischanet/memo-discord-bot#6]
エラーログです。
```
[ec2-user@ip-172-31-43-112 repos]$ sudo journalctl --follow -u memo-discord-bot
-- Logs begin at Tue 2018-12-25 16:40:37 UTC. --
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Function.Module._load (internal/modules/cjs/loader.js:552:3)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: memo-discord-bot.service: main process exited, code=exited, status=1/FAILURE
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: Unit memo-discord-bot.service entered failed state.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: memo-discord-bot.service failed.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: memo-discord-bot.service holdoff time over, scheduling restart.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: start request repeated too quickly for memo-discord-bot.service
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: Failed to start JavaScript Discord Bot Agent.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: Unit memo-discord-bot.service entered failed state.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: memo-discord-bot.service failed.
```

**Comment by yhay81** [comment]
詳細
```
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal systemd[1]: Starting JavaScript Discord Bot Agent...
-- Subject: Unit memo-discord-bot.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit memo-discord-bot.service has begun starting up.
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: internal/modules/cjs/loader.js:605
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: throw err;
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: ^
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: Error: Cannot find module '/home/ec2-user/repos/memo-discord-bot/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node'
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Function.Module._load (internal/modules/cjs/loader.js:529:25)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Module.require (internal/modules/cjs/loader.js:657:17)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at require (internal/modules/cjs/helpers.js:22:18)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Object.<anonymous> (/home/ec2-user/repos/memo-discord-bot/node_modules/sqlite3/lib/sqlite3.js:4:15)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Module._compile (internal/modules/cjs/loader.js:721:30)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Module.load (internal/modules/cjs/loader.js:620:32)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
Dec 29 02:39:36 ip-172-31-43-112.ap-northeast-1.compute.internal node[1157]: at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by yhay81** [comment]
`/home/ec2-user/repos/memo-discord-bot/node_modules/sqlite3/lib/binding/node-v67-linux-x64/node_sqlite3.node`
こういうのはなくて、あるのは
`/home/ec2-user/repos/memo-discord-bot/node_modules/sqlite3/lib/binding/node-v63-linux-x64/node_sqlite3.node`になってる

**Comment by yhay81** [comment]
ビルド環境と実行環境違う問題で起きるトラブルのようです。
パイプライン側の問題なので、こちらでなんとかします。
ビルド環境はubuntu/node v10がAWS CodeDeployのデフォルトで用意されてるのでそれを使っています。

対応策としては、
- 実行環境でインストールする
- ビルド環境を実行環境に合わせる
- 利用nodeバージョンをビルド環境に合わせる
などがありそうです。
本質的な解決のためには「ビルド環境を実行環境に合わせる」べきだろうと思いますがAWS CodeBuild的に簡単にできなさそうなら、別の方法も検討します。

**Comment by yhay81** [comment]
全体を安定版のv10に合わせました
